export type Lesson = {
  /** Actual YouTube video ID; repeated playlist entries are deduplicated. */
  id: string;
  title: string;
  /** One-based learning order: numbered video sessions first, supplements last. */
  position: number;
  durationSeconds?: number;
  /** First one-based position in the publisher's source playlist. */
  sourcePosition?: number;
  /** All source positions when the publisher repeats the same video. */
  sourcePositions?: number[];
  /** Video session number from its title, never a written-module number. */
  sessionNumber?: number;
};

export type LearningCourse = {
  id: string;
  title: string;
  subtitle: string;
  speaker: string;
  playlistId: string;
  sourceUrl: string;
  dailyMinutes: number;
  lessons: Lesson[];
};

// Curated, verified English recordings only. The refresh script uses this same
// allowlist and requires a review if a selected video's title changes.
export const englishPrabhupadaSelections = [
  { id: 'V6hmXsFUy2w', title: 'Knowledge | Srila Prabhupada English Lecture' },
] as const;

// Public metadata snapshot: 2026-09-28T15:21:46.710Z
// Refreshed with scripts/refresh-learning-catalog.ts. See docs/LEARNING-SOURCES.md.
// Unique videos follow video-session order; original positions remain on each lesson.
export const learningCourses: LearningCourse[] = [
  {
    id: 'soulful-japa',
    title: 'Soulful Japa',
    subtitle: 'Madhu Pandit Dasa · ISKCON Bangalore Sanga',
    speaker: 'Madhu Pandit Dasa',
    playlistId: 'PLKVQRAZMT7-kNyVocJzO1MXqsvimBMOMy',
    dailyMinutes: 30,
    sourceUrl: 'https://www.youtube.com/playlist?list=PLKVQRAZMT7-kNyVocJzO1MXqsvimBMOMy',
    lessons: [
      {
        id: 'BZiZtt80gyQ',
        title:
          'Soulful Japa : Session 1 : Lord Sri Krishna has incarnated again as Nama Avatara-Module 1',
        position: 1,
        sourcePosition: 1,
        sessionNumber: 1,
        durationSeconds: 909,
      },
      {
        id: 'im4fsM_E_fw',
        title: 'Soulful Japa : Session 2 :Outline or Journey towards Soulful Japa-Module 2',
        position: 2,
        sourcePosition: 2,
        sessionNumber: 2,
        durationSeconds: 2247,
      },
      {
        id: 'B0d2uC9-dh4',
        title:
          'Soulful Japa : Session 3 : Japa is not just a process but a relationship with Krishna-Module 3',
        position: 3,
        sourcePosition: 3,
        sessionNumber: 3,
        durationSeconds: 2577,
      },
      {
        id: 'ir5igQ2KZLQ',
        title:
          'Soulful Japa : Session 4 : Mindless japa, Mindful japa, and Soulful japa - Module 4',
        position: 4,
        sourcePosition: 4,
        sessionNumber: 4,
        durationSeconds: 2903,
      },
      {
        id: 'xliIiEl46z4',
        title: 'Soulful Japa : Session 5 : On background context of devotional service - Module 5',
        position: 5,
        sourcePosition: 5,
        sessionNumber: 5,
        durationSeconds: 2074,
      },
      {
        id: 'IfbdyUpP9C4',
        title:
          'Soulful Japa : Session 6 : How a sound uttered by material tongue can be God? - Module 6',
        position: 6,
        sourcePosition: 6,
        sessionNumber: 6,
        durationSeconds: 2836,
      },
      {
        id: 'HOxdLzjh_ik',
        title: 'Soulful Japa : Session 7 : The principle of Nāma Avatāra - Module 7',
        position: 7,
        sourcePosition: 7,
        sessionNumber: 7,
        durationSeconds: 2679,
      },
      {
        id: 'DkkbbIRfCWg',
        title:
          'Soulful Japa:Session 8:Namavatara as combination of Aprākrta Nāma Prabhu&empowered Śaktyāvēşa Nāma-1',
        position: 8,
        sourcePosition: 8,
        sessionNumber: 8,
        durationSeconds: 2781,
      },
      {
        id: 'Jhb-tvldPe8',
        title:
          'Soulful Japa:Session 9:Namavatara as combination of Aprākrta Nāma Prabhu&empowered Śaktyāvēşa Nāma-2',
        position: 9,
        sourcePosition: 9,
        sessionNumber: 9,
        durationSeconds: 3665,
      },
      {
        id: 'w37G5bLI5HM',
        title:
          "Soulful Japa:Session 10:The Absolute Name of Krishna isn't Name-Sound vibration of this world Part 1",
        position: 10,
        sourcePosition: 10,
        sessionNumber: 10,
        durationSeconds: 2754,
      },
      {
        id: 'f0gfH402JiU',
        title:
          "Soulful Japa:Session 11:The Absolute Name of Krishna isn't Name-Sound vibration of this world Part 2",
        position: 11,
        sourcePosition: 11,
        sessionNumber: 11,
        durationSeconds: 2454,
      },
      {
        id: '-PoWxCQ6itk',
        title:
          'Soulful Japa:Session 12:Our journey of self-purification & awakening of the spiritual mind-Module 10',
        position: 12,
        sourcePosition: 12,
        sessionNumber: 12,
        durationSeconds: 2792,
      },
      {
        id: 'n786t_0B5QM',
        title:
          'Soulful Japa:Session 13:Attention-touch and our sleeping and dreaming spiritual mind:Part 1-Module11',
        position: 13,
        sourcePosition: 13,
        sessionNumber: 13,
        durationSeconds: 2876,
      },
      {
        id: 'kXPB744QNsU',
        title:
          'Soulful Japa:Session 14:Attention-touch and our sleeping and dreaming spiritual mind:Part 2-Module11',
        position: 14,
        sourcePosition: 14,
        sessionNumber: 14,
        durationSeconds: 2745,
      },
      {
        id: 'J8Sq_Dnijvs',
        title:
          'Soulful Japa:Session 15:Attention-touch and our sleeping and dreaming spiritual mind:Part 3-Module11',
        position: 15,
        sourcePosition: 15,
        sessionNumber: 15,
        durationSeconds: 2643,
      },
      {
        id: 'OicZZaMPcZU',
        title:
          'Soulful Japa:Session16:Relationship between Aprākrta Nama Prabhu &  Śaktyāvēşa Nama:Part 1-Module12',
        position: 16,
        sourcePosition: 16,
        sessionNumber: 16,
        durationSeconds: 2825,
      },
      {
        id: 'jkK4aDw4Apg',
        title:
          'Soulful Japa:Session17:Relationship between Aprākrta Nama Prabhu &  Śaktyāvēşa Nama:Part 2-Module12',
        position: 17,
        sourcePosition: 17,
        sessionNumber: 17,
        durationSeconds: 2689,
      },
      {
        id: 'wsY4ZcnxrYs',
        title:
          'Soulful Japa : Session 18 : Summary Points, Key Concepts & Analogies from Module 1 to 8',
        position: 18,
        sourcePosition: 18,
        sessionNumber: 18,
        durationSeconds: 2880,
      },
      {
        id: 'jOPUJuqRW-M',
        title:
          'Soulful Japa: Session 19 : Summary Points, Key Concepts & Analogies from Module 8 to 12',
        position: 19,
        sourcePosition: 19,
        sessionNumber: 19,
        durationSeconds: 2628,
      },
      {
        id: 'vKnkQgtwtmo',
        title:
          'Soulful Japa:Session 20 :Revealing Experience- The Gardner Story & Impact of Golden Quotes-Module 38',
        position: 20,
        sourcePosition: 20,
        sessionNumber: 20,
        durationSeconds: 2589,
      },
      {
        id: 'WjAY61-4TMQ',
        title:
          'Soulful Japa: Session 21 : Golden Quotes- Golden Directions-Training Session Begins - Module 38',
        position: 21,
        sourcePosition: 21,
        sessionNumber: 21,
        durationSeconds: 2964,
      },
      {
        id: 'vWlzwtrMFWA',
        title: 'Soulful Japa: Session 22 : Can we develop taste for Chanting Overnight? -Module 38',
        position: 22,
        sourcePosition: 22,
        sessionNumber: 22,
        durationSeconds: 2017,
      },
      {
        id: 'gfEbWgmQUl4',
        title:
          'Soulful Japa: Session 23: Rain of Mercy-Isolated Chant&hear vs Concurrent Hear & chant-Module 38-53',
        position: 23,
        sourcePosition: 23,
        sessionNumber: 23,
        durationSeconds: 2209,
      },
      {
        id: 'kcUBD_rO2Ds',
        title:
          'Soulful Japa: Session 24 : Will familiarity for Golden Quotes breed Contempt? - Module 38-53',
        position: 24,
        sourcePosition: 24,
        sessionNumber: 24,
        durationSeconds: 2730,
      },
      {
        id: '2AgVcz8ve94',
        title:
          'Soulful Japa: Session 25 : Strengthen Background Mind to Link Chanting & Hearing -Module 38-53',
        position: 25,
        sourcePosition: 25,
        sessionNumber: 25,
        durationSeconds: 2932,
      },
      {
        id: 'P9tfzQMFhaY',
        title:
          'Soulful Japa:Session 26:How to trigger  Background Seva Bhavana for Sevya(Holy Name)?-Module 38-53',
        position: 26,
        sourcePosition: 26,
        sessionNumber: 26,
        durationSeconds: 3551,
      },
      {
        id: 'jvAUH7Fdsdg',
        title:
          'Soulful Japa:Session27:Hearing Hare Krishna or Knowing Hare Krishna:What is difference?-Module 38-53',
        position: 27,
        sourcePosition: 27,
        sessionNumber: 27,
        durationSeconds: 3392,
      },
      {
        id: 'ucUwUqws8g8',
        title: 'Soulful Japa : Session 28 : Obstacles during Practice Period - Module 38-53',
        position: 28,
        sourcePosition: 28,
        sessionNumber: 28,
        durationSeconds: 3369,
      },
      {
        id: 'BzI4sAM45tw',
        title:
          'Soulful Japa : Session 29 : Remove the Weeds: Envy, Pride ,Vanity and Self-importance - Module 38-53',
        position: 29,
        sourcePosition: 29,
        sessionNumber: 29,
        durationSeconds: 3589,
      },
      {
        id: 'Lis7jHu2e4g',
        title:
          'Soulful Japa:Session 30:Speaking the Sound & Knowing “the Sound”&Holding the Attention-Module 38-53',
        position: 30,
        sourcePosition: 30,
        sessionNumber: 30,
        durationSeconds: 3381,
      },
      {
        id: 'zbJePuZQ8zs',
        title:
          'Soulful Japa:Session 31:Create and Train a New Mind Slice : Mind Slice for Mindful Japa-Module 38-53',
        position: 31,
        sourcePosition: 31,
        sessionNumber: 31,
        durationSeconds: 3699,
      },
      {
        id: 'NjFdTOqGV6Q',
        title:
          'Soulful Japa: Session 32 : Diamond Quotes for Implementing Golden Quotes - Module 43',
        position: 32,
        sourcePosition: 32,
        sessionNumber: 32,
        durationSeconds: 3755,
      },
      {
        id: '5vdoBfEeWD8',
        title:
          'Soulful Japa : Session 33 : Doing-Effort as Leader and Knowing-Effort as Follower - Module 52',
        position: 33,
        sourcePosition: 33,
        sessionNumber: 33,
        durationSeconds: 3305,
      },
      {
        id: 'bxMuvDSCVns',
        title:
          "Soulful Japa : Session 34 : Can we think of Krishna's form or pastimes while doing Japa? - Module 53",
        position: 34,
        sourcePosition: 34,
        sessionNumber: 34,
        durationSeconds: 3461,
      },
      {
        id: 'T4V4gJZff7U',
        title:
          'Soulful Japa: Session 35 :Secret is Linking: Training Mind to Link Chanting and Hearing-Module 38-53',
        position: 35,
        sourcePosition: 35,
        sessionNumber: 35,
        durationSeconds: 3075,
      },
      {
        id: '5MRimntipuw',
        title: 'Soulful Japa: Session 36 : Rerun on Module 38 (Training Module) - Module 38',
        position: 36,
        sourcePosition: 36,
        sessionNumber: 36,
        durationSeconds: 3305,
      },
      {
        id: 'AeJyakoCSAQ',
        title:
          'Soulful Japa: Session 37 : Chanting with Srila Prabhupada along with Golden Quotes. - Module 38-53',
        position: 37,
        sourcePosition: 37,
        sessionNumber: 37,
        durationSeconds: 2933,
      },
      {
        id: 'PaJLXrn_7dk',
        title: 'Soulful Japa: Session 38 : Key Points Analyzed : 37 -53 Modules - Module 54',
        position: 38,
        sourcePosition: 38,
        sessionNumber: 38,
        durationSeconds: 3176,
      },
      {
        id: 'zZfOfZ9elt4',
        title:
          'Soulful Japa: Session 39 : Preparing Background Spirit for Module 11 &12 : Module 11(part 1)',
        position: 39,
        sourcePosition: 39,
        sessionNumber: 39,
        durationSeconds: 3653,
      },
      {
        id: '-B1w4yJPzH8',
        title: 'Soulful japa session 40 : Hallucinating & Dreamy Mind - Module 11 (Part 1)',
        position: 40,
        sourcePosition: 40,
        sessionNumber: 40,
        durationSeconds: 3576,
      },
      {
        id: '4NqF3sSVPLM',
        title:
          'Soulful Japa: Session 41 : Attention- Connection/ Attention- Touch : Module 11 (Part 1)',
        position: 41,
        sourcePosition: 41,
        sessionNumber: 41,
        durationSeconds: 3796,
      },
      {
        id: 'SIm1lzp5KZk',
        title: 'Soulful Japa: Session 42 : Touch Nama Prabhu Everyday by Attention Embrace!',
        position: 42,
        sourcePosition: 42,
        sessionNumber: 42,
        durationSeconds: 4188,
      },
      {
        id: 'dYE5_L4BG7g',
        title: 'Soulful Japa : Session 43 : A Dangerous Virus for Attentive Japa: THINKING VIRUS!',
        position: 43,
        sourcePosition: 43,
        sessionNumber: 43,
        durationSeconds: 4055,
      },
      {
        id: 'g4Dr4TF9Hio',
        title: 'Soulful Japa: Session 44 : Krishna & Krishna’s name is beyond material reality!',
        position: 44,
        sourcePosition: 44,
        sessionNumber: 44,
        durationSeconds: 4531,
      },
      {
        id: 'NBFFA_aE32Q',
        title: 'Soulful Japa: Session 45 : Welcome II-VIP (Infinitely Important-VIP) Everyday!',
        position: 45,
        sourcePosition: 45,
        sessionNumber: 45,
        durationSeconds: 3951,
      },
      {
        id: '5b4mLI7sgR4',
        title: 'Soulful Japa: Session 46 : What Krishna Thinks about his own Name? Let’s Know',
        position: 46,
        sourcePosition: 46,
        sessionNumber: 46,
        durationSeconds: 4415,
      },
      {
        id: 'ZwXoWTjLjgc',
        title: 'Soulful Japa: Session 47 : Sound Incarnation & Deity Incarnation: Similarities',
        position: 47,
        sourcePosition: 47,
        sessionNumber: 47,
        durationSeconds: 4503,
      },
      {
        id: 'ASeTLwVroDY',
        title: 'Soulful Japa: Session 48 : Nourishment for Soul: 16 Attentive Rounds!',
        position: 48,
        sourcePosition: 48,
        sessionNumber: 48,
        durationSeconds: 3886,
      },
      {
        id: 'CLQ04bJVGQY',
        title: 'Soulful Japa : Session 49 : Holy Name: Drink it through hearing',
        position: 49,
        sourcePosition: 49,
        sessionNumber: 49,
        durationSeconds: 4991,
      },
      {
        id: '7BZba3A4xM0',
        title:
          'Soulful Japa: Session 50 : Tasking Delight: Pleasure of Accomplishing & accumulating',
        position: 50,
        sourcePosition: 50,
        sessionNumber: 50,
        durationSeconds: 4127,
      },
      {
        id: 'ruSLDljctZc',
        title: 'Soulful Japa: Session 51 : Be Jubilant: Supreme Lord is a Person!',
        position: 51,
        sourcePosition: 51,
        sessionNumber: 51,
        durationSeconds: 4185,
      },
      {
        id: 'uw8ZxhLdTiA',
        title: 'Soulful Japa: Session 52 : Absolute Feelings come from Absolute Thoughts',
        position: 52,
        sourcePosition: 52,
        sessionNumber: 52,
        durationSeconds: 4153,
      },
      {
        id: '8bQrMgTyxww',
        title: 'Soulful Japa: Session 53 : Delightfully chant, joyfully hear and successfully task',
        position: 53,
        sourcePosition: 53,
        sessionNumber: 53,
        durationSeconds: 4173,
      },
      {
        id: 'vANtz8-Ubzw',
        title: 'Soulful Japa: Session 54 : Japa is best when uninterrupted',
        position: 54,
        sourcePosition: 54,
        sessionNumber: 54,
        durationSeconds: 4657,
      },
      {
        id: 'CqENelJLiXQ',
        title: 'Soulful Japa: Session 55 : Create Servant Consciousness, Not Master Consciousness!',
        position: 55,
        sourcePosition: 55,
        sessionNumber: 55,
        durationSeconds: 4136,
      },
      {
        id: 'Yl9wrhTHTys',
        title: 'Soulful Japa: Session 56 : Holy Name reciprocates with the Chanter',
        position: 56,
        sourcePosition: 56,
        sessionNumber: 56,
        durationSeconds: 4246,
      },
      {
        id: 'OP0v2AS_RVE',
        title: 'Soulful Japa: Session 57',
        position: 57,
        sourcePosition: 57,
        sessionNumber: 57,
        durationSeconds: 4324,
      },
      {
        id: 'rCsWeGCqQ6E',
        title: 'Soulful Japa: Session 58',
        position: 58,
        sourcePosition: 58,
        sessionNumber: 58,
        durationSeconds: 4584,
      },
      {
        id: 'Zo1Noe_JECg',
        title: 'Soulful Japa: Session 59',
        position: 59,
        sourcePosition: 59,
        sessionNumber: 59,
        durationSeconds: 4236,
      },
      {
        id: '-Bclb_Qg6zk',
        title: 'Soulful Japa: Session 60',
        position: 60,
        sourcePosition: 60,
        sessionNumber: 60,
        durationSeconds: 4602,
      },
      {
        id: '1ZErQDx4KV0',
        title: 'Soulful Japa: Session 61',
        position: 61,
        sourcePosition: 61,
        sessionNumber: 61,
        durationSeconds: 4432,
      },
      {
        id: 'gzSx-IEeIV4',
        title: 'Soulful Japa: Session 62',
        position: 62,
        sourcePosition: 62,
        sessionNumber: 62,
        durationSeconds: 4358,
      },
      {
        id: 'AbzlUj9gBg4',
        title: 'Soulful Japa: Session 63',
        position: 63,
        sourcePosition: 63,
        sessionNumber: 63,
        durationSeconds: 4651,
      },
      {
        id: 'dEThXx99G2c',
        title: 'Soulful Japa: Session 64',
        position: 64,
        sourcePosition: 64,
        sessionNumber: 64,
        durationSeconds: 4381,
      },
      {
        id: '52GOqddWIj8',
        title: 'Soulful Japa: Session 65',
        position: 65,
        sourcePosition: 65,
        sessionNumber: 65,
        durationSeconds: 4122,
      },
      {
        id: '_msacru7iuk',
        title: 'Soulful Japa: Session 66',
        position: 66,
        sourcePosition: 66,
        sessionNumber: 66,
        durationSeconds: 4654,
      },
      {
        id: 'Xsw-oGJXf1c',
        title: 'Soulful Japa: Session 67',
        position: 67,
        sourcePosition: 67,
        sessionNumber: 67,
        durationSeconds: 4440,
      },
      {
        id: 'ih4hxEmKP8s',
        title: 'Soulful Japa: Session 68',
        position: 68,
        sourcePosition: 68,
        sessionNumber: 68,
        durationSeconds: 4373,
      },
      {
        id: 'apBOOX8X62E',
        title: 'Soulful Japa: Session 69',
        position: 69,
        sourcePosition: 69,
        sessionNumber: 69,
        durationSeconds: 4536,
      },
      {
        id: 'I4HTyRY9LtE',
        title: 'Soulful Japa: Session 70',
        position: 70,
        sourcePosition: 70,
        sessionNumber: 70,
        durationSeconds: 4496,
      },
      {
        id: 'g6b73nduVAQ',
        title: 'Soulful Japa: Session 71',
        position: 71,
        sourcePosition: 71,
        sessionNumber: 71,
        durationSeconds: 4490,
      },
      {
        id: 'Oopdij0awXU',
        title: 'Soulful Japa: Session 72',
        position: 72,
        sourcePosition: 72,
        sessionNumber: 72,
        durationSeconds: 4514,
      },
      {
        id: 'woGkVYpR-yA',
        title: 'Soulful Japa: Session 73',
        position: 73,
        sourcePosition: 73,
        sessionNumber: 73,
        durationSeconds: 3989,
      },
      {
        id: 'DCFtWL3_BaI',
        title: 'Soulful Japa: Session 74',
        position: 74,
        sourcePosition: 74,
        sessionNumber: 74,
        durationSeconds: 4370,
      },
      {
        id: 'f5q0jdduON0',
        title: 'Soulful Japa: Session 75',
        position: 75,
        sourcePosition: 75,
        sessionNumber: 75,
        durationSeconds: 3939,
      },
      {
        id: '0ZKatj4q1Bg',
        title: 'Soulful Japa: Session 76',
        position: 76,
        sourcePosition: 76,
        sessionNumber: 76,
        durationSeconds: 2993,
      },
      {
        id: 'lKLsQ4AfjQM',
        title: 'Soulful Japa: Session 77',
        position: 77,
        sourcePosition: 77,
        sessionNumber: 77,
        durationSeconds: 4105,
      },
      {
        id: 'JGuzAhZEZ80',
        title: 'Soulful Japa: Session 78 (Sraddha)',
        position: 78,
        sourcePosition: 78,
        sessionNumber: 78,
        durationSeconds: 3927,
        sourcePositions: [78, 103],
      },
      {
        id: 'baJHIbfry48',
        title: 'Soulful Japa: Session 79',
        position: 79,
        sourcePosition: 79,
        sessionNumber: 79,
        durationSeconds: 3510,
        sourcePositions: [79, 110],
      },
      {
        id: 'F1PSK8_vHz4',
        title: 'Soulful Japa: Session 80 (SRADDHA)',
        position: 80,
        sourcePosition: 80,
        sessionNumber: 80,
        durationSeconds: 3800,
      },
      {
        id: 'nQFg0wlozOc',
        title: 'Soulful Japa: Session 81',
        position: 81,
        sourcePosition: 81,
        sessionNumber: 81,
        durationSeconds: 4551,
        sourcePositions: [81, 114],
      },
      {
        id: 'TCRHxRHkKQE',
        title: 'Soulful Japa: Session 82 (Begging for Mercy)',
        position: 82,
        sourcePosition: 82,
        sessionNumber: 82,
        durationSeconds: 3867,
      },
      {
        id: 'q7tttiXUmxk',
        title: 'Soulful Japa: Session 83',
        position: 83,
        sourcePosition: 83,
        sessionNumber: 83,
        durationSeconds: 3003,
        sourcePositions: [83, 116],
      },
      {
        id: 'RIYyxGEZyNM',
        title: 'Soulful Japa: Session 84',
        position: 84,
        sourcePosition: 84,
        sessionNumber: 84,
        durationSeconds: 3697,
        sourcePositions: [84, 107],
      },
      {
        id: 'fFUp-CdWn6Y',
        title: 'Soulful Japa: Session 85',
        position: 85,
        sourcePosition: 85,
        sessionNumber: 85,
        durationSeconds: 3578,
        sourcePositions: [85, 112],
      },
      {
        id: 'ywzxokzfq88',
        title: 'Soulful Japa: Session 86',
        position: 86,
        sourcePosition: 86,
        sessionNumber: 86,
        durationSeconds: 4455,
        sourcePositions: [86, 117],
      },
      {
        id: 'nqqjyXE4L5k',
        title: 'Soulful Japa: Session 87',
        position: 87,
        sourcePosition: 87,
        sessionNumber: 87,
        durationSeconds: 3932,
        sourcePositions: [87, 115],
      },
      {
        id: '94szQszpdT8',
        title: 'Soulful Japa: Session 88',
        position: 88,
        sourcePosition: 88,
        sessionNumber: 88,
        durationSeconds: 4042,
        sourcePositions: [88, 101],
      },
      {
        id: '-WkKffEBI0g',
        title: 'Soulful Japa: Session 89',
        position: 89,
        sourcePosition: 89,
        sessionNumber: 89,
        durationSeconds: 3071,
        sourcePositions: [89, 100],
      },
      {
        id: 'e62t_FfwlPQ',
        title: 'Soulful Japa: Session 90',
        position: 90,
        sourcePosition: 90,
        sessionNumber: 90,
        durationSeconds: 2046,
        sourcePositions: [90, 111],
      },
      {
        id: 'UnpUDHgf1hQ',
        title: 'Soulful Japa: Session 91',
        position: 91,
        sourcePosition: 91,
        sessionNumber: 91,
        durationSeconds: 3988,
        sourcePositions: [91, 108],
      },
      {
        id: 'LnF2Mtx5_vY',
        title: 'Soulful Japa: Session 92',
        position: 92,
        sourcePosition: 92,
        sessionNumber: 92,
        durationSeconds: 3701,
        sourcePositions: [92, 105],
      },
      {
        id: 'PLuIuDuveQk',
        title: 'Soulful Japa: Session 93',
        position: 93,
        sourcePosition: 93,
        sessionNumber: 93,
        durationSeconds: 3840,
        sourcePositions: [93, 106],
      },
      {
        id: 'YPJHlxVSWNI',
        title: 'Soulful Japa: Session 94',
        position: 94,
        sourcePosition: 94,
        sessionNumber: 94,
        durationSeconds: 3903,
        sourcePositions: [94, 109],
      },
      {
        id: 'Dh3caQXlu2Y',
        title: 'Soulful Japa: Session 95',
        position: 95,
        sourcePosition: 95,
        sessionNumber: 95,
        durationSeconds: 3938,
        sourcePositions: [95, 102],
      },
      {
        id: 'zYfTEoOg2ZM',
        title: 'Soulful Japa: Session 96',
        position: 96,
        sourcePosition: 96,
        sessionNumber: 96,
        durationSeconds: 4046,
        sourcePositions: [96, 118],
      },
      {
        id: '-GhND-zjUwg',
        title: 'Soulful Japa : Session 97',
        position: 97,
        sourcePosition: 97,
        sessionNumber: 97,
        durationSeconds: 3435,
        sourcePositions: [97, 99],
      },
      {
        id: 'LCNAkm1jadk',
        title: 'Soulful Japa: Session 97',
        position: 98,
        sourcePosition: 104,
        sessionNumber: 97,
        durationSeconds: 3965,
      },
      {
        id: 'gb_vQiLEROM',
        title: 'Soulful Japa : Session 98',
        position: 99,
        sourcePosition: 98,
        sessionNumber: 98,
        durationSeconds: 4866,
        sourcePositions: [98, 113],
      },
      {
        id: 'ryApMSDHYzg',
        title:
          'Develop the Desire to Chant Each Round Attentively | Sri Madhu Pandit Dasa | Soulful Japa Training',
        position: 100,
        sourcePosition: 119,
        durationSeconds: 1924,
      },
    ],
  },
  {
    id: 'happiness-pleasure',
    title: 'Krishna Consciousness Happiness & Pleasure',
    subtitle: 'Madhu Pandit Dasa · ISKCON Bangalore Sanga',
    speaker: 'Madhu Pandit Dasa',
    playlistId: 'PLKVQRAZMT7-k1hMlGnAmNT8uMpfw68HNO',
    dailyMinutes: 30,
    sourceUrl: 'https://www.youtube.com/playlist?list=PLKVQRAZMT7-k1hMlGnAmNT8uMpfw68HNO',
    lessons: [
      {
        id: 'X6YQZcLKd9c',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 1',
        position: 1,
        sourcePosition: 1,
        sessionNumber: 1,
        durationSeconds: 3250,
      },
      {
        id: '218L9cFM5Wk',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 2',
        position: 2,
        sourcePosition: 2,
        sessionNumber: 2,
        durationSeconds: 3531,
      },
      {
        id: '5WTe05OmVII',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 3',
        position: 3,
        sourcePosition: 3,
        sessionNumber: 3,
        durationSeconds: 3469,
      },
      {
        id: 'r-KoLq_VIiw',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 4',
        position: 4,
        sourcePosition: 4,
        sessionNumber: 4,
        durationSeconds: 3041,
      },
      {
        id: 'QOli-BSChxM',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 5',
        position: 5,
        sourcePosition: 5,
        sessionNumber: 5,
        durationSeconds: 3190,
      },
      {
        id: '2tyr7PYsMp8',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 6',
        position: 6,
        sourcePosition: 6,
        sessionNumber: 6,
        durationSeconds: 3579,
      },
      {
        id: 'eBjA1KP8Q8Q',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 7',
        position: 7,
        sourcePosition: 7,
        sessionNumber: 7,
        durationSeconds: 3077,
      },
      {
        id: 'DbH7es09faQ',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 8',
        position: 8,
        sourcePosition: 8,
        sessionNumber: 8,
        durationSeconds: 3176,
      },
      {
        id: 'rWmmSTzLaAw',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 9',
        position: 9,
        sourcePosition: 9,
        sessionNumber: 9,
        durationSeconds: 3055,
      },
      {
        id: 'gyl6sVXEyg8',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 10',
        position: 10,
        sourcePosition: 10,
        sessionNumber: 10,
        durationSeconds: 3109,
      },
      {
        id: '0IWUHOTTNC0',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 11',
        position: 11,
        sourcePosition: 11,
        sessionNumber: 11,
        durationSeconds: 2945,
      },
      {
        id: 'herMS016dtg',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 12',
        position: 12,
        sourcePosition: 12,
        sessionNumber: 12,
        durationSeconds: 3112,
      },
      {
        id: 'IEkauMx8iFY',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 13',
        position: 13,
        sourcePosition: 13,
        sessionNumber: 13,
        durationSeconds: 3714,
      },
      {
        id: 'Bk3O2ZW_Eko',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 14',
        position: 14,
        sourcePosition: 14,
        sessionNumber: 14,
        durationSeconds: 3793,
      },
      {
        id: 'mC3htZtX1Gg',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 15',
        position: 15,
        sourcePosition: 15,
        sessionNumber: 15,
        durationSeconds: 2866,
      },
      {
        id: 'abJyRu5k1ME',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 16',
        position: 16,
        sourcePosition: 16,
        sessionNumber: 16,
        durationSeconds: 3596,
      },
      {
        id: 'vddb1kmfhks',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 17',
        position: 17,
        sourcePosition: 17,
        sessionNumber: 17,
        durationSeconds: 3919,
      },
      {
        id: 'yF03NCYyJb8',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 18',
        position: 18,
        sourcePosition: 18,
        sessionNumber: 18,
        durationSeconds: 4151,
      },
      {
        id: '4UHWxKTctS4',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 19',
        position: 19,
        sourcePosition: 19,
        sessionNumber: 19,
        durationSeconds: 4234,
      },
      {
        id: '0mTYD25_VLw',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 20',
        position: 20,
        sourcePosition: 20,
        sessionNumber: 20,
        durationSeconds: 4416,
      },
      {
        id: 'ZsCgNkcuyXo',
        title: 'Krishna Consciousness Happiness & Pleasure: Session 21',
        position: 21,
        sourcePosition: 21,
        sessionNumber: 21,
        durationSeconds: 2174,
      },
    ],
  },
  {
    id: 'prabhupada',
    title: 'Hear Śrīla Prabhupāda',
    subtitle: 'Selected English lectures · The Acharya',
    speaker: 'Śrīla Prabhupāda',
    playlistId: '',
    sourceUrl: 'https://www.youtube.com/channel/UCDTX-lo7YZCg_P28_Mo4NOg',
    dailyMinutes: 30,
    lessons: [
      {
        id: 'V6hmXsFUy2w',
        title: 'Knowledge | Srila Prabhupada English Lecture',
        position: 1,
      },
    ],
  },
];
